# Encoding: UTF-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# WARNING: this is development only! should be removed when deploying.

# Clearing current objects.

Warehouse::delete_all
Server::delete_all
Camera::delete_all
User::delete_all

warehouse_id = Warehouse::create(label: 'Armazém 9-A').id

server_id = Server::create(label: 'SRV-ROCHA-AZ-9A',
                           address: '201.64.223.150',
                           username: 'admin',
                           password: 'VIDEO!edge23',
                           warehouse_id: warehouse_id).id

['CF-01 SALA MONITORAMENTO',
 'CF-02 HIDRANTE',
 'CF-01 SALA MONITORAMENTO',
 'CF-02 HIDRANTE',
 'CF-03 CORREDOR PORTAO 2',
 'CF-04 ARMARIOS',
 'CF-05 CORREDOR BOX 30 A 15',
 'CF-06 CENTRAL BOX 15 A 30',
 'CF-07 CORREDOR A DO PORTAO 4',
 'CF-08 CORREDOR DO BOX 15',
 'CF-09 PLACA DO PORTAO 4',
 'CF-10 PORTAO 4 PARA A RUA',
 'CF-11 RUA PARA O PORTAO 4',
 'CF-12 GAIOLA DE GLP',
 'CF-13 CORREDOR DO BOX 14',
 'CF-14 CORREDOR B DO PORTAO 4',
 'CF-15 GERADOR',
 'CF-16 VISTORIA DO PORTAO 3 INTERNO',
 'CF-17 VISTORIA DO PORTAO 3 EXTERNA 1',
 'CF-18 VISTORIA DO PORTAO 3 EXTERNA 2',
 'CF-19 PATIO CENTRAL DO PORTAO 3',
 'CF-20 PATIO GERADOR NO PORTAO 3',
 'CF-21 VISTORIA DO PORTAO 2 EXTERNA 1',
 'CF-22 VISTORIA DO PORTAO 2 EXTERNA 2',
 'CF-23 PATIO REDUZIDO',
 'CF-24 PATIO DA RFB',
 'CF-25 VISTORIA DO PORTAO 2 INTERNA',
 'CF-26 PORTAO 1 PARA A RUA',
 'CF-27 CONTROLE DE ACESSO',
 'CF-28 PLACA DO PORTAO 1',
 'CM-29 SPEED DOME ARMAZEM'].each_with_index do |c, i|
  Camera::create(label: c, camera_id: i+1, server_id: server_id)
end

warehouse_id = Warehouse::create(label: 'Armazém Bunge').id

server_id = Server::create(label: 'SRV-ROCHA-AZBUNGE-01',
                           address: '201.64.223.151',
                           username: 'admin',
                           password: 'VIDEO!edge23',
                           warehouse_id: warehouse_id).id

['CF-01 ACESSO SALA TI - PREDIO ADMINISTRATIVO',
 'CF-02 PORTAO ACESSO PRINCIPAL - PREDIO ADMINISTRATIVO',
 'CF-03 VISAO DAS PORTAS DA CABINE DE MEDICAO',
 'CF-04 VISAO PERIMETRO RUA MANOEL BONIFACIO 1',
 'CF-05 VISAO PERIMETRO RUA MANOEL BONIFACIO 2',
 'CF-06 VISAO GERAL DO PATIO - COLUNA TC-3 PROXIMO MURO',
 'CF-07 PORTAL ACESSO TORNIQUETE SOB TC-3',
 'CF-08 VISAO GERAL DO PATIO - FIXADA NA TORRE TC-3',
 'CF-09 PORTA DE ACESSO TC-3',
 'CF-10 CAPTURA PLACAS DOS VEICULOS BL RODOVIARIA 03',
 'CF-11 CAPTURA PLACAS DOS VEICULOS BL RODOVIARIA 02',
 'CF-12 CAPTURA PLACAS DOS VEICULOS BL RODOVIARIA 01',
 'CF-13 VISAO GERAL DESCARGA BL RODOVIARIA 1',
 'CF-14 VISAO GERAL DESCARGA BL RODOVIARIA 2',
 'CF-15 PORTA DE ACESSO TC-2',
 'CF-16 VISAO GERAL SAIDA BL RODOVIARIA',
 'CF-17 VISAO PERIMETRO BL RODOVIARIA MANOEL RIBAS 1',
 'CF-18 VISAO PERIMETRO BL RODOVIARIA MANOEL RIBAS 2',
 'CF-19 PORTAO ENTRADA DE VEICULOS BL RODOVIARIA',
 'CF-20 VISAO GERAL ENTRADA VEICULOS BL RODOVIARIA M. RIBAS',
 'CF-21 DISPLAY BL RODOVIARIA 01',
 'CF-22 DISPLAY BL RODOVIARIA 02',
 'CF-23 DISPLAY BL RODOVIARIA 03',
 'CF-24 PLACAS VEICULOS GATE OUT',
 'CF-25 VISAO GERAL DA SAIDA GATE OUT',
 'CF-26 PERIMETRO ACESSO FERROVIARIO',
 'CF-27 PERIMETRO LINHA FERREA FUNDOS TERMINAL 1',
 'CF-28 PERIMETRO LINHA FERREA FUNDOS TERMINAL 2',
 'CM-29 SPD DOME VISAO GERAL LINHA FERREA FDS TERM.',
 'CF-30 DISPLAY BALANCA RODOFERROVIARIA 01',
 'CF-31 DISPLAY BALANCA RODOFERROVIARIA 02',
 'CF-32 ACESSO PNE - ESCRITORIO',
 'CF-33 CAPTURA PLACAS VEICULOS - BL FERROVIARIA 1',
 'CF-34 CAPTURA PLACAS VEICULOS - BL FERROVIARIA 2',
 'CF-35 VISAO GERAL PATIO - BL RODOFERROVIARIA',
 'CF-36 PORTA ACESSO TULHA BL RODOFERROVIARIA 1',
 'CF-37 PORTA ACESSO TULHA BL RODOFERROVIARIA 2',
 'CF-83 SALA DE MONITORAMENTO',
 'CF-39 VISAO PORTAO ACESSO L FERREA - BL FERROVIARIA',
 'CF-40 VISAO GERAL PATIO - LATERAL BL RODOFERROVIARIA'].each_with_index do |c, i|
  Camera::create(label: c, camera_id: i+1, server_id: server_id)
end

server_id = Server::create(label: 'SRV-ROCHA-AZBUNGE-02',
                           address: '201.64.223.152',
                           username: 'admin',
                           password: 'VIDEO!edge23',
                           warehouse_id: warehouse_id).id

['CM-41 SPD DOME VISAO GERAL - PORTOES LINHA FERREA',
 'CF-42 VISAO GERAL PORTOES LN FERREA - PATIO VAGOES',
 'CF-43 PORTA DE ACESSO TC-6',
 'CF-44 PORTA DE ACESSO TC-7',
 'CF-45 CAPTURA PLACAS VEICULOS ENTRADA ARMAZEM',
 'CF-46 PORTA ACESSO ARMAZEM VISAO INTERNA/EXT.1',
 'CF-47 PORTA ACESSO ARMAZEM VISAO INTERNA/EXT.2',
 'CF-48 VISAO GERAL DO ARMAZEM INTERNO - ROTA 90',
 'CF-49 PORTAL ACESSO TORNIQUETE ARMAZEM',
 'CF-50 PORTA DE ACESSO AO TC-5',
 'CF-51 VISAO GERAL PORTAO ACESSO LN FERREA - ROTA 90',
 'CF-52 VISAO PORTAO ACESSO LN FERREA - PATIO VAGOES',
 'CF-53 VISAO GERAL ESTACIONAMENTO 1',
 'CF-54 VISAO GERAL ESTACIONAMENTO 2',
 'CF-55 VISAO GERAL PORTAO LN FERREA-PATIO VAGOES 1',
 'CF-56 VISAO GERAL PORTAO LN FERREA-PATIO VAGOES 2',
 'CF-57 DISPLAY DA BALANCA DE FLUXO',
 'CF-58 TAMPA DA CELULA DE CARGA - BL FLUXO 1',
 'CF-59 TAMPA DA CELULA DE CARGA - BL FLUXO 2',
 'CF-60 TAMPA DA CELULA DE CARGA - BL FLUXO 3',
 'CF-61 TAMPA DA CELULA DE CARGA - BL FLUXO 4',
 'CF-62 PERIMETRO AV. CORONEL JOSE LOGO',
 'CF-63 VISAO GERAL PATIO VAGOES - TORRE BL DE FLUXO',
 'CF-64 PERIMETRO AV. AYRTON SENNA DA SILVA',
 'CF-65 TORRE TRANSFERENCIA BL FLUXO-VISAO SOB ESTEIRA',
 'CF-66 PORTA ACESSO TORRE TRANSF. BL FLUXO PAV.1',
 'CF-67 PORTA ACESSO TORRE TRANSF. BL FLUXO PAV.1',
 'CF-68 VISAO INT. ESTEIRAS ENTRE BL FLUXO E TORRE C.F.',
 'CF-69 VISAO GERAL BL FERROVIARIA',
 'CF-70 VISAO INTERNA ESTEIRAS ENTRE APPA/BL FLUXO 1',
 'CF-71 VISAO INTERNA ESTEIRAS ENTRE APPA/BL FLUXO 2',
 'CF-72 VISAO INTERNA DAS ESTEIRAS BIFURCADOR APPA',
 'CM-73 SPD DOME PATIO VAGOES - TORRE BL FLUXO',
 'CF-74 BIFURCADOR PARA O AZ PRACA E MARGARIDA',
 'CF-75 BIFURCADOR PARA O AZ BUNGE',
 'CF-76 VISAO ESTEIRA BL DE FLUXO',
 'CF-77 VISAO PERIMETRO E ACESSO CASA FORCA',
 'CF-78 PERIMETRO AV. GOV. MANOEL RIBAS',
 'CF-79 PERIMETRO AV. CORONEL JOSE LOBO 1',
 'CF-80 VISAO GERAL INTERNA DO ARMAZEM',
 'CF-81 PERIMETRO AV. CORONEL JOSE LOBO 2',
 'CF-82 ACESSO PNE - GUARITA ARMAZEM'].each_with_index do |c, i|
  Camera::create(label: c, camera_id: i+1, server_id: server_id)
end

User::create(username: 'Administrador',
             password: 'ibtech',
             password_confirmation: 'ibtech')